#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dierenarts
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dierendb")]
	public partial class dierenartsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbaas_dier(baas_dier instance);
    partial void Updatebaas_dier(baas_dier instance);
    partial void Deletebaas_dier(baas_dier instance);
    partial void Insertbaa(baa instance);
    partial void Updatebaa(baa instance);
    partial void Deletebaa(baa instance);
    partial void Insertafspraak(afspraak instance);
    partial void Updateafspraak(afspraak instance);
    partial void Deleteafspraak(afspraak instance);
    partial void Insertdier(dier instance);
    partial void Updatedier(dier instance);
    partial void Deletedier(dier instance);
    #endregion
		
		public dierenartsDataContext() : 
				base(global::dierenarts.Properties.Settings.Default.dierendbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dierenartsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dierenartsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dierenartsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dierenartsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<baas_dier> baas_diers
		{
			get
			{
				return this.GetTable<baas_dier>();
			}
		}
		
		public System.Data.Linq.Table<baa> baas
		{
			get
			{
				return this.GetTable<baa>();
			}
		}
		
		public System.Data.Linq.Table<afspraak> afspraaks
		{
			get
			{
				return this.GetTable<afspraak>();
			}
		}
		
		public System.Data.Linq.Table<dier> diers
		{
			get
			{
				return this.GetTable<dier>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.baas_dier")]
	public partial class baas_dier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _baasid;
		
		private int _dierid;
		
		private EntityRef<baa> _baa;
		
		private EntityRef<dier> _dier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbaasidChanging(int value);
    partial void OnbaasidChanged();
    partial void OndieridChanging(int value);
    partial void OndieridChanged();
    #endregion
		
		public baas_dier()
		{
			this._baa = default(EntityRef<baa>);
			this._dier = default(EntityRef<dier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baasid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int baasid
		{
			get
			{
				return this._baasid;
			}
			set
			{
				if ((this._baasid != value))
				{
					if (this._baa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnbaasidChanging(value);
					this.SendPropertyChanging();
					this._baasid = value;
					this.SendPropertyChanged("baasid");
					this.OnbaasidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dierid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int dierid
		{
			get
			{
				return this._dierid;
			}
			set
			{
				if ((this._dierid != value))
				{
					if (this._dier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndieridChanging(value);
					this.SendPropertyChanging();
					this._dierid = value;
					this.SendPropertyChanged("dierid");
					this.OndieridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="baa_baas_dier", Storage="_baa", ThisKey="baasid", OtherKey="baasid", IsForeignKey=true)]
		public baa baa
		{
			get
			{
				return this._baa.Entity;
			}
			set
			{
				baa previousValue = this._baa.Entity;
				if (((previousValue != value) 
							|| (this._baa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._baa.Entity = null;
						previousValue.baas_diers = null;
					}
					this._baa.Entity = value;
					if ((value != null))
					{
						value.baas_diers = this;
						this._baasid = value.baasid;
					}
					else
					{
						this._baasid = default(int);
					}
					this.SendPropertyChanged("baa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dier_baas_dier", Storage="_dier", ThisKey="dierid", OtherKey="dierid", IsForeignKey=true)]
		public dier dier
		{
			get
			{
				return this._dier.Entity;
			}
			set
			{
				dier previousValue = this._dier.Entity;
				if (((previousValue != value) 
							|| (this._dier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dier.Entity = null;
						previousValue.baas_diers = null;
					}
					this._dier.Entity = value;
					if ((value != null))
					{
						value.baas_diers = this;
						this._dierid = value.dierid;
					}
					else
					{
						this._dierid = default(int);
					}
					this.SendPropertyChanged("dier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.baas")]
	public partial class baa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _baasid;
		
		private string _voornaam;
		
		private string _achternaam;
		
		private string _adres;
		
		private string _postcode;
		
		private string _woonplaats;
		
		private System.Nullable<int> _telefoon;
		
		private string _email;
		
		private EntityRef<baas_dier> _baas_diers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbaasidChanging(int value);
    partial void OnbaasidChanged();
    partial void OnvoornaamChanging(string value);
    partial void OnvoornaamChanged();
    partial void OnachternaamChanging(string value);
    partial void OnachternaamChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void OnpostcodeChanging(string value);
    partial void OnpostcodeChanged();
    partial void OnwoonplaatsChanging(string value);
    partial void OnwoonplaatsChanged();
    partial void OntelefoonChanging(System.Nullable<int> value);
    partial void OntelefoonChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public baa()
		{
			this._baas_diers = default(EntityRef<baas_dier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baasid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int baasid
		{
			get
			{
				return this._baasid;
			}
			set
			{
				if ((this._baasid != value))
				{
					this.OnbaasidChanging(value);
					this.SendPropertyChanging();
					this._baasid = value;
					this.SendPropertyChanged("baasid");
					this.OnbaasidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_voornaam", DbType="NChar(50)")]
		public string voornaam
		{
			get
			{
				return this._voornaam;
			}
			set
			{
				if ((this._voornaam != value))
				{
					this.OnvoornaamChanging(value);
					this.SendPropertyChanging();
					this._voornaam = value;
					this.SendPropertyChanged("voornaam");
					this.OnvoornaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_achternaam", DbType="NChar(50)")]
		public string achternaam
		{
			get
			{
				return this._achternaam;
			}
			set
			{
				if ((this._achternaam != value))
				{
					this.OnachternaamChanging(value);
					this.SendPropertyChanging();
					this._achternaam = value;
					this.SendPropertyChanged("achternaam");
					this.OnachternaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="NChar(50)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postcode", DbType="NChar(50)")]
		public string postcode
		{
			get
			{
				return this._postcode;
			}
			set
			{
				if ((this._postcode != value))
				{
					this.OnpostcodeChanging(value);
					this.SendPropertyChanging();
					this._postcode = value;
					this.SendPropertyChanged("postcode");
					this.OnpostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_woonplaats", DbType="NChar(50)")]
		public string woonplaats
		{
			get
			{
				return this._woonplaats;
			}
			set
			{
				if ((this._woonplaats != value))
				{
					this.OnwoonplaatsChanging(value);
					this.SendPropertyChanging();
					this._woonplaats = value;
					this.SendPropertyChanged("woonplaats");
					this.OnwoonplaatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoon", DbType="Int")]
		public System.Nullable<int> telefoon
		{
			get
			{
				return this._telefoon;
			}
			set
			{
				if ((this._telefoon != value))
				{
					this.OntelefoonChanging(value);
					this.SendPropertyChanging();
					this._telefoon = value;
					this.SendPropertyChanged("telefoon");
					this.OntelefoonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="baa_baas_dier", Storage="_baas_diers", ThisKey="baasid", OtherKey="baasid", IsUnique=true, IsForeignKey=false)]
		public baas_dier baas_diers
		{
			get
			{
				return this._baas_diers.Entity;
			}
			set
			{
				baas_dier previousValue = this._baas_diers.Entity;
				if (((previousValue != value) 
							|| (this._baas_diers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._baas_diers.Entity = null;
						previousValue.baa = null;
					}
					this._baas_diers.Entity = value;
					if ((value != null))
					{
						value.baa = this;
					}
					this.SendPropertyChanged("baas_diers");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.afspraak")]
	public partial class afspraak : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _afspraakid;
		
		private System.Nullable<System.DateTime> _datum;
		
		private string _tijd;
		
		private string _afspraaksoort;
		
		private System.Nullable<int> _dierid;
		
		private EntityRef<dier> _dier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnafspraakidChanging(int value);
    partial void OnafspraakidChanged();
    partial void OndatumChanging(System.Nullable<System.DateTime> value);
    partial void OndatumChanged();
    partial void OntijdChanging(string value);
    partial void OntijdChanged();
    partial void OnafspraaksoortChanging(string value);
    partial void OnafspraaksoortChanged();
    partial void OndieridChanging(System.Nullable<int> value);
    partial void OndieridChanged();
    #endregion
		
		public afspraak()
		{
			this._dier = default(EntityRef<dier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_afspraakid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int afspraakid
		{
			get
			{
				return this._afspraakid;
			}
			set
			{
				if ((this._afspraakid != value))
				{
					this.OnafspraakidChanging(value);
					this.SendPropertyChanging();
					this._afspraakid = value;
					this.SendPropertyChanged("afspraakid");
					this.OnafspraakidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datum", DbType="Date")]
		public System.Nullable<System.DateTime> datum
		{
			get
			{
				return this._datum;
			}
			set
			{
				if ((this._datum != value))
				{
					this.OndatumChanging(value);
					this.SendPropertyChanging();
					this._datum = value;
					this.SendPropertyChanged("datum");
					this.OndatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tijd", DbType="VarChar(50)")]
		public string tijd
		{
			get
			{
				return this._tijd;
			}
			set
			{
				if ((this._tijd != value))
				{
					this.OntijdChanging(value);
					this.SendPropertyChanging();
					this._tijd = value;
					this.SendPropertyChanged("tijd");
					this.OntijdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_afspraaksoort", DbType="NChar(50)")]
		public string afspraaksoort
		{
			get
			{
				return this._afspraaksoort;
			}
			set
			{
				if ((this._afspraaksoort != value))
				{
					this.OnafspraaksoortChanging(value);
					this.SendPropertyChanging();
					this._afspraaksoort = value;
					this.SendPropertyChanged("afspraaksoort");
					this.OnafspraaksoortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dierid", DbType="Int")]
		public System.Nullable<int> dierid
		{
			get
			{
				return this._dierid;
			}
			set
			{
				if ((this._dierid != value))
				{
					if (this._dier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndieridChanging(value);
					this.SendPropertyChanging();
					this._dierid = value;
					this.SendPropertyChanged("dierid");
					this.OndieridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dier_afspraak", Storage="_dier", ThisKey="dierid", OtherKey="dierid", IsForeignKey=true)]
		public dier dier
		{
			get
			{
				return this._dier.Entity;
			}
			set
			{
				dier previousValue = this._dier.Entity;
				if (((previousValue != value) 
							|| (this._dier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dier.Entity = null;
						previousValue.afspraaks.Remove(this);
					}
					this._dier.Entity = value;
					if ((value != null))
					{
						value.afspraaks.Add(this);
						this._dierid = value.dierid;
					}
					else
					{
						this._dierid = default(Nullable<int>);
					}
					this.SendPropertyChanged("dier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dier")]
	public partial class dier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dierid;
		
		private string _naam;
		
		private string _diersoort;
		
		private EntityRef<baas_dier> _baas_diers;
		
		private EntitySet<afspraak> _afspraaks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndieridChanging(int value);
    partial void OndieridChanged();
    partial void OnnaamChanging(string value);
    partial void OnnaamChanged();
    partial void OndiersoortChanging(string value);
    partial void OndiersoortChanged();
    #endregion
		
		public dier()
		{
			this._baas_diers = default(EntityRef<baas_dier>);
			this._afspraaks = new EntitySet<afspraak>(new Action<afspraak>(this.attach_afspraaks), new Action<afspraak>(this.detach_afspraaks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dierid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dierid
		{
			get
			{
				return this._dierid;
			}
			set
			{
				if ((this._dierid != value))
				{
					this.OndieridChanging(value);
					this.SendPropertyChanging();
					this._dierid = value;
					this.SendPropertyChanged("dierid");
					this.OndieridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam", DbType="NChar(10)")]
		public string naam
		{
			get
			{
				return this._naam;
			}
			set
			{
				if ((this._naam != value))
				{
					this.OnnaamChanging(value);
					this.SendPropertyChanging();
					this._naam = value;
					this.SendPropertyChanged("naam");
					this.OnnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diersoort", DbType="NChar(10)")]
		public string diersoort
		{
			get
			{
				return this._diersoort;
			}
			set
			{
				if ((this._diersoort != value))
				{
					this.OndiersoortChanging(value);
					this.SendPropertyChanging();
					this._diersoort = value;
					this.SendPropertyChanged("diersoort");
					this.OndiersoortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dier_baas_dier", Storage="_baas_diers", ThisKey="dierid", OtherKey="dierid", IsUnique=true, IsForeignKey=false)]
		public baas_dier baas_diers
		{
			get
			{
				return this._baas_diers.Entity;
			}
			set
			{
				baas_dier previousValue = this._baas_diers.Entity;
				if (((previousValue != value) 
							|| (this._baas_diers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._baas_diers.Entity = null;
						previousValue.dier = null;
					}
					this._baas_diers.Entity = value;
					if ((value != null))
					{
						value.dier = this;
					}
					this.SendPropertyChanged("baas_diers");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dier_afspraak", Storage="_afspraaks", ThisKey="dierid", OtherKey="dierid")]
		public EntitySet<afspraak> afspraaks
		{
			get
			{
				return this._afspraaks;
			}
			set
			{
				this._afspraaks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_afspraaks(afspraak entity)
		{
			this.SendPropertyChanging();
			entity.dier = this;
		}
		
		private void detach_afspraaks(afspraak entity)
		{
			this.SendPropertyChanging();
			entity.dier = null;
		}
	}
}
#pragma warning restore 1591
